require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/bundle'
Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'app/policies/**/*'
Rails/I18nLocaleTexts:
  Enabled: false
Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy